SELECT A.*
  FROM (SELECT CASE
                 WHEN RCV.TRANSACTION_DATE IS NULL THEN
                  'Pendiente por ingresar'
                 ELSE
                  'Recepcionada'
               END AS ESTADO_RQ,
               (select NAME
                  from hr_operating_units
                 where ORGANIZATION_ID = PRHA.REQ_BU_ID) UNIDAD_NEGOCIO,
               (SELECT HR.NAME
                  FROM HR_ALL_ORGANIZATION_UNITS HR
                 WHERE HR.organization_id = PRLA.DESTINATION_ORGANIZATION_ID) AS ALMACEN,
               (SELECT ORG.ORGANIZATION_CODE
                  FROM INV_ORG_PARAMETERS ORG
                 WHERE ORG.organization_id = PRLA.DESTINATION_ORGANIZATION_ID) AS CODIGO_ALMACEN,
               PRLA.DESTINATION_SUBINVENTORY AS SUBINVENTARIO,
               PRHA.REQUISITION_NUMBER AS RQ,
               TO_CHAR(PRHA.CREATION_DATE, 'DD/MM/YYYY') AS FECHA_CREACION,
               (SELECT DISTINCT FULL_NAME
                  FROM PER_PERSON_NAMES_F
                 WHERE PERSON_ID = PRHA.PREPARER_ID
                   AND ROWNUM = 1) AS SOLICITANTE,
               NVL(PRHA.DESCRIPTION, PRHA.JUSTIFICATION) AS JUSTIFICACION,
               NVL((SELECT HA.SEGMENT1
                      FROM PO_HEADERS_ALL  HA,
                           PO_LINES_ALL    PLA
                     WHERE HA.PO_HEADER_ID = PLA.FROM_HEADER_ID
                       AND PLA.PO_HEADER_ID = POH.PO_HEADER_ID
                       AND ROWNUM = 1), ' ') AS ACUERDO,
               POH.SEGMENT1 AS NRO_OC,
               TO_CHAR(POH.CREATION_DATE, 'DD/MM/YYYY') AS FEC_CREA_OC,
               (SELECT DISTINCT DISPLAY_NAME
                  FROM PER_PERSON_NAMES_F
                 WHERE PERSON_ID = POH.AGENT_ID
                   AND NAME_TYPE = 'CO'
                   AND ROWNUM = 1) AS COMPRADOR,
               POH.ATTRIBUTE5 AS AREA_SOLI,
               POH.ATTRIBUTE4 AS ADMIN_CONTRATO,
               TO_CHAR(PRLA.NEED_BY_DATE, 'DD/MM/YYYY') AS FECHA_ENTREGA,
               (SELECT DISTINCT PSU.VENDOR_NAME
                  FROM POZ_SUPPLIERS_V PSU
                 WHERE PSU.VENDOR_ID = POH.VENDOR_ID) AS PROVEEDOR,
               PRLA.LINE_NUMBER AS LINEA,
               ESI.ITEM_NUMBER AS CODIGO_ARTICULO,
               PRLA.ITEM_DESCRIPTION AS DESCRIPCION,
              (SELECT PLLA.QUANTITY
                  FROM PO_LINE_LOCATIONS_ALL PLLA
                 WHERE PLLA.PO_LINE_ID = PRLA.PO_LINE_ID)AS CANTIDAD,
               PRLA.UOM_CODE AS UNIDAD_MEDIDA,
               (SELECT PLLA.PRICE_OVERRIDE
                  FROM PO_LINE_LOCATIONS_ALL PLLA
                 WHERE PLLA.PO_LINE_ID = PRLA.PO_LINE_ID) AS VALOR_UNI,
               (SELECT PLLA.QUANTITY * PLLA.PRICE_OVERRIDE
                  FROM PO_LINE_LOCATIONS_ALL PLLA
                 WHERE PLLA.PO_LINE_ID = PRLA.PO_LINE_ID) AS VALOR_ORDENADO,
               (SELECT (NVL(PLLA.AMOUNT_BILLED,0) + NVL(ZL.TAX_AMT,0)) 
                  FROM PO_LINE_LOCATIONS_ALL   PLLA,
                       ZX_LINES                ZL
                 WHERE ZL.TRX_ID = PLLA.PO_HEADER_ID
                   AND ZL.TRX_LINE_ID = PLLA.LINE_LOCATION_ID
                   AND PLLA.LINE_LOCATION_ID = PRLA.PO_LINE_ID) AS VALOR_TOTAL,
               PRLA.CURRENCY_CODE AS MONEDA,
               RCV.QUANTITY AS CANT_RECIBIDA,
               TO_CHAR(RCV.TRANSACTION_DATE, 'DD/MM/YYYY') AS FECHA_RECEP,
               (SELECT DISTINCT ITL.TRANSACTION_TYPE_NAME
                  FROM INV_MATERIAL_TXNS IMT, INV_TRANSACTION_TYPES_TL ITL
                 WHERE IMT.RCV_TRANSACTION_ID = RCV.TRANSACTION_ID
                   AND IMT.TRANSACTION_TYPE_ID = ITL.TRANSACTION_TYPE_ID
                   AND ITL.LANGUAGE = 'E') AS TIPO_TRANS,
               (SELECT DISTINCT RSH.RECEIPT_NUM
                  FROM rcv_shipment_headers RSH
                 WHERE RSH.SHIPMENT_HEADER_ID = RCV.SHIPMENT_HEADER_ID) AS NRO_RECEP,
               (SELECT DISTINCT imt.TRANSACTION_ID
                  FROM INV_MATERIAL_TXNS IMT
                 WHERE IMT.RCV_TRANSACTION_ID = RCV.TRANSACTION_ID) AS NRO_TRANS,
               RCV.TRANSACTION_ID AS NRO_TRANS_RECEP,
               (SELECT HL.INTERNAL_LOCATION_CODE
                  FROM HR_LOCATIONS HL
                 WHERE HL.LOCATION_ID = PRLA.DELIVER_TO_LOCATION_ID) AS LOCALIZADOR,
               RCV.CREATED_BY AS CREADO_POR,
               (SELECT DISTINCT AIA.INVOICE_NUM FROM AP_INVOICES_ALL AIA,
					AP_INVOICE_LINES_ALL AIL
					WHERE AIA.INVOICE_ID =AIL.INVOICE_ID
					AND AIL.LINE_TYPE_LOOKUP_CODE = 'ITEM'
					AND AIA.APPROVAL_STATUS != 'CANCELLED'
					AND AIL.RCV_TRANSACTION_ID= RCV.PARENT_TRANSACTION_ID
					AND ROWNUM = 1) AS FACTURA, 
                 (SELECT DISTINCT TO_CHAR(AIA.INVOICE_DATE, 'DD/MM/YYYY')
				 FROM AP_INVOICES_ALL AIA,
					AP_INVOICE_LINES_ALL AIL
					WHERE AIA.INVOICE_ID =AIL.INVOICE_ID
					AND AIL.LINE_TYPE_LOOKUP_CODE = 'ITEM'
					AND AIA.APPROVAL_STATUS != 'CANCELLED'
					AND AIL.RCV_TRANSACTION_ID= RCV.PARENT_TRANSACTION_ID
					AND ROWNUM = 1) AS FECHA_FACTURA,
                  (SELECT DISTINCT AIA.APPROVAL_STATUS
				 FROM AP_INVOICES_ALL AIA,
					AP_INVOICE_LINES_ALL AIL
					WHERE AIA.INVOICE_ID =AIL.INVOICE_ID
					AND AIL.LINE_TYPE_LOOKUP_CODE = 'ITEM'
					AND AIA.APPROVAL_STATUS != 'CANCELLED'
					AND AIL.RCV_TRANSACTION_ID= RCV.PARENT_TRANSACTION_ID
					AND ROWNUM = 1) AS ESTADO_FACTURA
          FROM POR_REQUISITION_HEADERS_ALL PRHA,
               POR_REQUISITION_LINES_ALL   PRLA,
               PO_LINE_TYPES_B             PLT,
               EGP_SYSTEM_ITEMS            ESI,
               EGP_SYSTEM_ITEMS_TL         EST,
               POR_REQ_DISTRIBUTIONS_ALL   PRDA,
               PO_DISTRIBUTIONS_ALL        PDA,
               PO_HEADERS_ALL              POH,
               RCV_TRANSACTIONS            RCV
         WHERE 1 = 1
              -- AND PRHA.REQUISITION_NUMBER = '40-RQ-0015-2022'
              --AND PRHA.LINE_GROUP != 'TRANSFER_ORDER'
              --AND NVL(PRHA.LINE_GROUP, 'REQUISITION') != 'TRANSFER_ORDER'
              --AND PRLA.CANCEL_DATE is null
           AND PRLA.REQUISITION_HEADER_ID = PRHA.REQUISITION_HEADER_ID
           AND PLT.LINE_TYPE_ID = PRLA.LINE_TYPE_ID
           AND PRLA.ITEM_ID = ESI.INVENTORY_ITEM_ID
           AND ESI.ORGANIZATION_ID = PRLA.DESTINATION_ORGANIZATION_ID
           AND EST.INVENTORY_ITEM_ID = ESI.INVENTORY_ITEM_ID
           AND EST.ORGANIZATION_ID = ESI.ORGANIZATION_ID
           AND EST.LANGUAGE = 'E'
           AND PRDA.REQUISITION_LINE_ID = PRLA.REQUISITION_LINE_ID
           AND PDA.REQ_DISTRIBUTION_ID = PRDA.DISTRIBUTION_ID
           AND POH.PO_HEADER_ID = PDA.PO_HEADER_ID
           AND RCV.PO_HEADER_ID(+) = PDA.PO_HEADER_ID
           AND RCV.PO_DISTRIBUTION_ID(+) = PDA.PO_DISTRIBUTION_ID
           AND RCV.TRANSACTION_TYPE(+) = 'DELIVER'
              --AND PRHA.DOCUMENT_STATUS = NVL(:P_ESTADO , PRHA.DOCUMENT_STATUS)
           AND to_char(PRHA.CREATION_DATE, 'DD/MM/YYYY') BETWEEN
               NVL(to_char(:p_desde, 'DD/MM/YYYY'),
                   to_char(PRHA.CREATION_DATE, 'DD/MM/YYYY')) AND
               NVL(to_char(:p_hasta, 'DD/MM/YYYY'),
                   to_char(PRHA.CREATION_DATE, 'DD/MM/YYYY'))
           AND to_char(PRLA.NEED_BY_DATE, 'DD/MM/YYYY') BETWEEN
               NVL(to_char(:p_desde_P, 'DD/MM/YYYY'),
                   to_char(PRLA.NEED_BY_DATE, 'DD/MM/YYYY')) AND
               NVL(to_char(:p_hasta_P, 'DD/MM/YYYY'),
                   to_char(PRLA.NEED_BY_DATE, 'DD/MM/YYYY'))
        -- AND to_char(PRLA.NEED_BY_DATE , 'DD/MM/YYYY') ) BETWEEN NVL(to_char(:p_desde_P , 'DD/MM/YYYY')), to_char(PRLA.NEED_BY_DATE , 'DD/MM/YYYY')  ) AND NVL(to_char(:p_hasta_P , 'DD/MM/YYYY')), to_char(PRLA.NEED_BY_DATE , 'DD/MM/YYYY') )
        UNION ALL
        SELECT DECODE(PHA.DOCUMENT_STATUS,
                      'CLOSED FOR RECEIVING','Recepcionada',
                      'Pendiente por ingresar') AS ESTADO_RQ,
               (SELECT HOU.NAME
                  FROM HR_OPERATING_UNITS HOU
                 WHERE HOU.ORGANIZATION_ID = PHA.REQ_BU_ID) UNIDAD_NEGOCIO,
               (SELECT HAOU.NAME
                  FROM HR_ALL_ORGANIZATION_UNITS HAOU
                 WHERE HAOU.LOCATION_ID = PLLA.SHIP_TO_LOCATION_ID ) AS ALMACEN,
               (SELECT IOP.ORGANIZATION_CODE
                  FROM HR_ALL_ORGANIZATION_UNITS  HAOU,
                       INV_ORG_PARAMETERS         IOP
                 WHERE IOP.ORGANIZATION_ID = HAOU.ORGANIZATION_ID
                   AND HAOU.LOCATION_ID = PLLA.SHIP_TO_LOCATION_ID) AS CODIGO_ALMACEN,
               (SELECT PDA.DESTINATION_SUBINVENTORY
			   FROM PO_DISTRIBUTIONS_ALL PDA
			   WHERE PDA.PO_HEADER_ID = PLA.PO_HEADER_ID
				AND PDA.PO_LINE_ID = PLA.PO_LINE_ID
				AND PDA.LINE_LOCATION_ID = PLLA.LINE_LOCATION_ID
			   ) AS SUBINVENTARIO,
               ' ' AS RQ,             --NO HAY RQ
               ' ' AS FECHA_CREACION, --NO HAY RQ
               PHA.ATTRIBUTE6 AS SOLICITANTE,
               PHA.COMMENTS AS JUSTIFICACION,
               NVL((SELECT HA.SEGMENT1
                      FROM PO_HEADERS_ALL  HA
                     WHERE HA.PO_HEADER_ID = PLA.FROM_HEADER_ID), ' ') AS ACUERDO,
               PHA.SEGMENT1 AS NRO_OC,
               TO_CHAR(PHA.CREATION_DATE, 'DD/MM/YYYY') AS FEC_CREA_OC,
                (SELECT DISTINCT DISPLAY_NAME
                  FROM PER_PERSON_NAMES_F
                 WHERE PERSON_ID = PHA.AGENT_ID
                   AND NAME_TYPE = 'CO'
                   AND ROWNUM = 1) AS COMPRADOR,
               PHA.ATTRIBUTE5 AS AREA_SOLI,
               PHA.ATTRIBUTE4 AS ADMIN_CONTRATO,
               TO_CHAR(PLLA.NEED_BY_DATE, 'DD/MM/YYYY') AS FECHA_ENTREGA,
               (SELECT DISTINCT PSU.VENDOR_NAME
                  FROM POZ_SUPPLIERS_V PSU
                 WHERE PSU.VENDOR_ID = PHA.VENDOR_ID) AS PROVEEDOR,
               PLA.LINE_NUM AS LINEA,
               ESIB.ITEM_NUMBER AS CODIGO_ARTICULO,
               PLA.ITEM_DESCRIPTION AS DESCRIPCION,
               PLA.QUANTITY AS CANTIDAD,
               PLA.UOM_CODE AS UNIDAD_MEDIDA,
               PLLA.PRICE_OVERRIDE AS VALOR_UNI,
               PLLA.PRICE_OVERRIDE * PLA.QUANTITY  AS VALOR_ORDENADO,
               ((PLLA.PRICE_OVERRIDE * PLA.QUANTITY) + NVL(ZL.TAX_AMT,0)) AS VALOR_TOTAL,
               PHA.CURRENCY_CODE AS MONEDA,
               RT.QUANTITY AS CANT_RECIBIDA,
               TO_CHAR(RT.TRANSACTION_DATE, 'DD/MM/YYYY') AS FECHA_RECEP,
               (SELECT DISTINCT ITL.TRANSACTION_TYPE_NAME
                  FROM INV_MATERIAL_TXNS        IMT, 
                       INV_TRANSACTION_TYPES_TL ITL
                 WHERE IMT.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
                   AND IMT.TRANSACTION_TYPE_ID = ITL.TRANSACTION_TYPE_ID
                   AND ITL.LANGUAGE = 'E') AS TIPO_TRANS,
               RSH.RECEIPT_NUM AS NRO_RECEP,
               (SELECT DISTINCT imt.TRANSACTION_ID
                  FROM INV_MATERIAL_TXNS IMT
                 WHERE IMT.RCV_TRANSACTION_ID = RT.TRANSACTION_ID) AS NRO_TRANS,
               RT.TRANSACTION_ID AS NRO_TRANS_RECEP,
               (SELECT HL.INTERNAL_LOCATION_CODE
                  FROM HR_LOCATIONS HL
                 WHERE HL.LOCATION_ID = PLLA.FINAL_DISCHARGE_LOCATION_ID) AS LOCALIZADOR,
               RT.CREATED_BY AS CREADO_POR,
               (SELECT DISTINCT AIA.INVOICE_NUM FROM AP_INVOICES_ALL AIA,
					AP_INVOICE_LINES_ALL AIL
					WHERE AIA.INVOICE_ID =AIL.INVOICE_ID
					AND AIL.LINE_TYPE_LOOKUP_CODE = 'ITEM'
					AND AIA.APPROVAL_STATUS != 'CANCELLED'
					AND AIL.RCV_TRANSACTION_ID= RT.PARENT_TRANSACTION_ID
					AND ROWNUM = 1) AS FACTURA, 
                 (SELECT DISTINCT TO_CHAR(AIA.INVOICE_DATE, 'DD/MM/YYYY')
				 FROM AP_INVOICES_ALL AIA,
					AP_INVOICE_LINES_ALL AIL
					WHERE AIA.INVOICE_ID =AIL.INVOICE_ID
					AND AIL.LINE_TYPE_LOOKUP_CODE = 'ITEM'
					AND AIA.APPROVAL_STATUS != 'CANCELLED'
					AND AIL.RCV_TRANSACTION_ID= RT.PARENT_TRANSACTION_ID
					AND ROWNUM = 1) AS FECHA_FACTURA,
                  (SELECT DISTINCT AIA.APPROVAL_STATUS
				 FROM AP_INVOICES_ALL AIA,
					AP_INVOICE_LINES_ALL AIL
					WHERE AIA.INVOICE_ID =AIL.INVOICE_ID
					AND AIL.LINE_TYPE_LOOKUP_CODE = 'ITEM'
					AND AIA.APPROVAL_STATUS != 'CANCELLED'
					AND AIL.RCV_TRANSACTION_ID= RT.PARENT_TRANSACTION_ID
					AND ROWNUM = 1) AS ESTADO_FACTURA
          FROM PO_HEADERS_ALL         PHA,
               PO_LINES_ALL           PLA,
               PO_LINE_LOCATIONS_ALL  PLLA,
               RCV_TRANSACTIONS       RT,
               RCV_SHIPMENT_LINES     RSL,
               RCV_SHIPMENT_HEADERS   RSH,
               EGP_SYSTEM_ITEMS_B     ESIB,
               ZX_LINES               ZL
         WHERE PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
           AND PLA.PO_LINE_ID = PLLA.PO_LINE_ID
           AND PLA.PO_HEADER_ID = RT.PO_HEADER_ID(+)
           AND PLA.PO_LINE_ID = RT.PO_LINE_ID(+)
           AND NVL(RT.TRANSACTION_TYPE,'DELIVER') IN ('DELIVER' , 'RETURN TO RECEIVING')
           AND PHA.PO_HEADER_ID = ZL.TRX_ID(+) 
           AND PLLA.LINE_LOCATION_ID = ZL.TRX_LINE_ID(+)
           AND NVL(ZL.ENTITY_CODE,'PURCHASE_ORDER') = 'PURCHASE_ORDER'
		   AND NVL(ZL.EVENT_CLASS_CODE , 'PO_PA') = 'PO_PA'
           AND PLA.ITEM_ID = ESIB.INVENTORY_ITEM_ID
           AND PLLA.SHIP_TO_ORGANIZATION_ID = ESIB.ORGANIZATION_ID
           AND PLLA.PO_HEADER_ID = RSL.PO_HEADER_ID(+)
           AND PLLA.PO_LINE_ID = RSL.PO_LINE_ID(+)
           AND RSL.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID(+)
		   AND RT.SHIPMENT_LINE_ID = RSL.SHIPMENT_LINE_ID(+)
           AND PHA.INTERFACE_SOURCE_CODE LIKE 'CARGA%'
           AND to_char(PHA.CREATION_DATE, 'DD/MM/YYYY') BETWEEN
               NVL(to_char(:p_desde, 'DD/MM/YYYY'),
                   to_char(PHA.CREATION_DATE, 'DD/MM/YYYY')) AND
               NVL(to_char(:p_hasta, 'DD/MM/YYYY'),
                   to_char(PHA.CREATION_DATE, 'DD/MM/YYYY'))
           AND to_char(PLLA.NEED_BY_DATE, 'DD/MM/YYYY') BETWEEN
               NVL(to_char(:p_desde_P, 'DD/MM/YYYY'),
                   to_char(PLLA.NEED_BY_DATE, 'DD/MM/YYYY')) AND
               NVL(to_char(:p_hasta_P, 'DD/MM/YYYY'),
                   to_char(PLLA.NEED_BY_DATE, 'DD/MM/YYYY'))
        ) A
 WHERE A.ESTADO_RQ = NVL(:P_ESTADO, A.ESTADO_RQ)
   AND A.RQ = NVL(:P_RQ, A.RQ)
   AND A.COMPRADOR = NVL(:P_COMPRADOR, A.COMPRADOR)
   AND A.NRO_OC = NVL(:P_NRO_OC, A.NRO_OC)
   AND A.CODIGO_ARTICULO = NVL(:P_CODIGO_ARTICULO, A.CODIGO_ARTICULO)