SELECT
--D.PLANNING_ELEMENT_ID,
--D.PERIOD_NAME as Period,
CONCAT( 'FY' ,  SUBSTR ( D.PERIOD_NAME ,5) ) as Year,
SUBSTR ( D.PERIOD_NAME ,1,3) as Month,

--E.PLANNING_START_DATE,
--E.PLANNING_END_DATE,

--E.PLAN_VERSION_ID,
--V.VERSION_NUMBER,

--E.ORGANIZATION_ID,
--P2.ORG_ID as Org_project,
ORG.NAME as Organization_Name,

E.PROJECT_ID,
P1.NAME AS Project_Name,
P2.SEGMENT1 as Project_Number,
P2.ATTRIBUTE6 as Area,
P2.ATTRIBUTE8 as Bloque,
P2.ATTRIBUTE1 as CeCo,
P2.ATTRIBUTE5 as Project_Type,

PROJECT_STATUS_CODE as EstatusProject,

--E.EXPENDITURE_TYPE_ID,
ET1.EXPENDITURE_TYPE_NAME,
ET2.ATTRIBUTE1 as Account,

--E.TASK_ID,
T1.NAME as Task_Name,

'USD' as REFMONEDA,

--D.PFC_RAW_COST, D.PFC_BRDND_COST, 
--D.TC_RAW_COST, D.TC_BRDND_COST, D.PC_RAW_COST,
D.PC_BRDND_COST

FROM 
pjo_plan_line_details D,
PJO_PLANNING_ELEMENTS E,
PJF_EXP_TYPES_TL ET1,
PJF_EXP_TYPES_B ET2,
PJF_PROJECTS_ALL_TL P1,
PJF_PROJECTS_ALL_B P2,
HR_ORGANIZATION_UNITS_F_TL ORG,
PJF_PROJ_ELEMENTS_TL T1,
PJO_PLAN_VERSIONS_B V

WHERE 
V.PLAN_STATUS_CODE = 'B'
and V.CURRENT_PLAN_STATUS_FLAG = 'Y'
and V.REQUEST_ID is not null
and PROJECT_STATUS_CODE = 'ACTIVE'
--and E.PROJECT_ID = '300000004866490'
--and ET2.ATTRIBUTE1  = '160511'

and E.PLANNING_ELEMENT_ID = D.PLANNING_ELEMENT_ID
and E.EXPENDITURE_TYPE_ID = ET1.EXPENDITURE_TYPE_ID
and E.EXPENDITURE_TYPE_ID = ET2.EXPENDITURE_TYPE_ID 
and E.PROJECT_ID = P1.PROJECT_ID
and E.PROJECT_ID = P2.PROJECT_ID
--and E.ORGANIZATION_ID = ORG.ORGANIZATION_ID
and P2.ORG_ID = ORG.ORGANIZATION_ID
and E.TASK_ID = T1.PROJ_ELEMENT_ID
and E.PLAN_VERSION_ID = V.PLAN_VERSION_ID

and ET1.LANGUAGE = 'US'
and P1.LANGUAGE = 'US'
and ORG.LANGUAGE = 'US'
and T1.LANGUAGE = 'US'

--and SUBSTR ( D.PERIOD_NAME ,1,3) = :P_Year
and CONCAT( 'FY' ,  SUBSTR ( D.PERIOD_NAME ,5) ) != :P_Period